name: deploying on staging
on: 
    push:
        branches:
            - "production"

jobs:
    redeploying_everything:
        name: deploying everything in the staging cluster
        runs-on: ubuntu-latest
        steps:
            - run: |
                echo "${{ secrets.VKI_2 }}" &> ~/ssh_key
                mkdir -p /home/runner/.ssh
                chmod 700 /home/runner/ssh_key

                ssh -o StrictHostKeyChecking=no -i ~/ssh_key ubuntu@43.204.115.13 -t "cd Ts-Final/ && git pull origin production && 
                export PATH="/home/ubuntu/.nvm/versions/node/v24.13.0/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/snap/bin" &&
                npm install -g pnpm && 
                pnpm install && 
                pnpm run build && 
                pm2 restart fe-server && 
                pm2 restart http-server &&
                pm2 restart ws-server "
