name: deploying on staging
on: 
    push:
        branches:
            - "main"

jobs:
    redeploying_everything:
        name: deploying everything in the staging cluster
        runs-on: ubuntu-latest
        steps:
            - run: |
                echo "${{ secrets.VKI_2 }}" > ~/ssh_key
                chmod 600 ~/ssh_key

                ssh -o StrictHostKeyChecking=no -i ~/ssh_key ubuntu@13.203.215.19 << 'EOF'
                cd Ts-Final
                git pull origin main

                export PATH=$PATH:/home/ubuntu/.nvm/versions/node/v24.13.0/bin

                pnpm install
                pnpm run build
                pm2 restart fe-server
                pm2 restart http-server
                pm2 restart ws-server
                EOF