name: deploying on staging
on: 
    push:
        branches:
            - "main"

jobs:
    redeploying_everything:
        name: deploying everything in the staging cluster
        runs-on: ubuntu-latest
        steps:
            - run: |
                mkdir -p ~/.ssh
                printf '%s\n' "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
                chmod 600 ~/.ssh/id_rsa
                ssh -o StrictHostKeyChecking=no ubuntu@13.203.215.19 "cd week-25-ci-next-app/ && git pull origin main && export PATH=/root/.nvm/versions/node/v22.13.1/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/snap/bin && npm install -g pnpm && pnpm install && pnpm run build && pm2 restart fe-server && pm2 restart http-server && pm2 restart ws-server"