name: deploying on staging
on: 
    push:
        branches:
            - "main"

jobs:
    redeploying_everything:
        name: deploying everything in the staging cluster
        runs-on: ubuntu-latest
        steps:
            - name: SSH Into server
              run: |
                echo ${{ secrets.VKI_2}} &> ~/ssh_key
                ssh -i ~/ssh_key ubuntu@13.203.215.19
                cd Ts-Final/ && git pull
                pnpm install
                pnpm run build
                pm2 restart fe-server
                pm2 restart http-server
                pm2 restart ws-server