name: deploying on staging
on: 
    push:
        branches:
            - "main"

jobs:
    redeploying_everything:
        name: deploying everything in the staging cluster
        runs-on: ubuntu-latest
        steps:
            - run: |
                echo "${{ secrets.SSH_PRIVATE_KEY }}" | tr -d '\r' &> ~/ssh_key
                chmod 700 /ssh_key
                ssh -o StrictHostKeyChecking=no -i ~/ssh_key ubuntu@13.203.215.19 -t "cd week-25-ci-next-app/ && git pull origin main && export PATH=/root/.nvm/versions/node/v22.13.1/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/snap/bin && npm install -g pnpm && pnpm install && pnpm run build && pm2 restart fe-sever && pm2 restart http-sever && pm2 restart ws-sever"